In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf


In [2]:
dataset=pd.read_csv("/content/drive/MyDrive/Dataset/Bank_Customers_Dataset.csv")


In [3]:
print(dataset.head())

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]


In [4]:
print(dataset)

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10

In [5]:
X=dataset.iloc[:,3:-1].values
Y=dataset.iloc[:,-1].values

print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(Y)

[1 0 1 ... 1 1 0]


**Encode Categorical Data**

In [7]:
# Encode categorical data (Gender) using Label Encoder
# Since we have only two categorical data

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])
# Apply label encoding on all the row and only on column of index 2

print(X)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
# Encode Categorical data using OneHotEncoder
# Since we have more than two categorical data

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])] , remainder='passthrough')

X=np.array(ct.fit_transform(X))
print(X)

# When we perform OneHotEncoder then dumy variable move to first column of the matrix features

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X,Y,test_size=0.20, random_state=0)



Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)



**Building the ANN**

Initializing the ANN

In [11]:
ann=tf.keras.models.Sequential()


Adding the input layer and the first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# Hyper parameter value i.e number of neuron in hidden layer is random not a fixed or thumb rule


Adding the input layer and the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


Adding the output layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


**Training the ANN**

Compiling the ANN

In [15]:
ann.compile(optimizer='adam', loss='binary_crossentropy' , metrics=['accuracy'] )


Training the ANN on Training set

In [16]:
# Fitting the ANN to the Training set
ann.fit(x_train, y_train, batch_size= 32,epochs=100 )



Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7763 - accuracy: 0.5278
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5149 - accuracy: 0.7922
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4633 - accuracy: 0.8035
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4403 - accuracy: 0.8144
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4293 - accuracy: 0.8151
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4198 - accuracy: 0.8171
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4112 - accuracy: 0.8190
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4034 - accuracy: 0.8192
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3965 - accuracy: 0.8263
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3893 - accura

**Making the predictions and evaluating the model**

Predicting the Test set results 

In [17]:
y_pred= ann.predict(x_test)
y_pred=(y_pred>0.5)

Details of customer for prediction

In [59]:
Country=1  # 0: ,1: ,2:
Credit_Score=950
Gender=1   # 0:Female, 1:Male
Age=40
Tenure=3
Balance=70000
Number_of_product=1
Has_CC=1   # 0: Has no Credit card, 1: Has Credit card
Is_Active_Customer=1   # 0:Not a active Customer, 1: Active Customer
Estimated_Salary=9000

New prediction

In [60]:
new_prediction=ann.predict(sc.transform(np.array([[1,0,1, Credit_Score, Gender, Age,Tenure, Balance, Number_of_product, Has_CC, Is_Active_Customer, Estimated_Salary]])))
# Country: France: 1,0,1  Spain:0,0,1 Germany: 0,1,0

# new_prediction=(new_prediction>0.5)

print(new_prediction)

if new_prediction>0.5:
  print("Customer will stay in Bank")
else:
  print("Customer may leave the Bank")

[[0.11503062]]
Customer may leave the Bank


**Confusion matrix**

In [61]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [21]:
print(cm)

[[1513   82]
 [ 189  216]]


**Accuracy**

In [62]:

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8645